### ISSUE TITLE
Create Registration page

### ISSUE THREAD

**Issue by jwu910** [yourstoryproject/yourstoryproject#47]
We should have a registration page -- a way to POST new users to db.

https://github.com/yourstoryproject/yourstoryproject/blob/master/docs/api/account.md

This page should be just a bare minimum simple HTML form that POSTS to the CREATE endpoint listed in the api docs above.

Minimum requirements:
* Registration Route
* Registration page
* Success/Fail notification

```
├── pyapp
│   ├── api
│   │   ├── Account.py
│   │   ├── Entry.py
│   │   └── Tag.py
│   ├── forms
│   │   └── LoginForm.py
│   ├── __init__.py
│   ├── models
│   │   ├── Account.py
│   │   ├── Entry.py
│   │   ├── __init__.py
│   │   └── Tag.py
│   ├── routes
│   │   ├── Account.py
│   │   ├── Entry.py
│   │   ├── __init__.py
│   │   └── Tag.py
│   ├── templates <---- create [registration.html] here
│   │   ├── api.html
│   │   ├── auth.html
│   │   ├── base.html
│   │   ├── index.html
│   │   └── login.html
│   └── utils
│       ├── auth.py
│       └── server.py
```

**Comment by rebeccahongsf** [comment]
I can try this :D

**Comment by jwu910** [comment]
Let me know if you have any questions!
